cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://localhost:8081,http://101.35.245.13:5173,http://101.35.245.13:3000

alipay.notify-url=http://localhost:8003/api/front/pay/alipay/notify
alipay.return-url=http://localhost:8003/api/front/pay/alipay/return
alipay.frontend-base-url=http://localhost:5173
